### PR TITLE
Update about.py

### PR DESCRIPTION
**Pull request by dikonov**
This commit should only be used if the parentheses matching problem in https://github.com/Huevos/SatScanLcn/pull/10 persists after https://github.com/Huevos/SatScanLcn/pull/12.

It escapes two parentheses within a string and may require copying this change into the new ru.po.

### CODE REVIEW

**Comment by Huevos** [comment]
Why do you need multiple pull requests?

Please make your mind up with one change, and test it before submitting. 

And please close all the other pull requests.

**Comment by dikonov** [comment]
I have no idea how to see this error. 

It is very strange that python tries to match ( and ]. These brackets are of different types. The log view in Enigma shows nothing and tells me that log files do not exist. I could not find any relevant logs in /var/log/ either.

**Comment by Huevos** [comment]
I can't believe you submitted a file without testing it. Please don't do that again.

I fixed it this morning. Here is what you did wrong: https://github.com/Huevos/SatScanLcn/commit/5b66621ebd56e3f655a7d66c2d6844c805c46b1f

**Comment by dikonov** [comment]
OK. All 3 versions worked for me and the error was not visible, so I had to guess. My bad that I did not notice the typo.

**Pull request closed without merging**
